#---------------------------------#
#  Build Image                    #
#---------------------------------#
image: Visual Studio 2017

#---------------------------------#
#  Build Script                   #
#---------------------------------#
build_script:
  - ps: .\build.ps1

# Tests
test: off

#---------------------------------#
#  Build Cache                    #
#---------------------------------#
cache:
  - tools -> build.cake # cake tools cache
  - '%USERPROFILE%\.nuget\packages -> **\project.json'  # project.json cache